# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 428de65dad85de3213e0a281ed50e756cad40475a7d9263a4d2f967251c1370827f9cb7144f0c095050abf97b6801b74ff90d24602346ee0fb5efa291eb7a535

test:
  secret_key_base: 5a6e061abba34f19a9d2c9b82ec5d5491df63a6c47b227e689b14afa32aa1b020ee740a133cc6358755e64c449b87a7eaa0aabb7344db158483717779e4dddd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
